"""`tools` command group — binary-backed geometry rewrites."""

from __future__ import annotations

import click
from lxml import etree

from cli_anything_inkstitch.binary import require, run_extension
from cli_anything_inkstitch.commands._helpers import open_project
from cli_anything_inkstitch.errors import UserError
from cli_anything_inkstitch.history import document_replace, make_entry, push
from cli_anything_inkstitch.output import emit


@click.group("tools")
def tools():
    """Binary-backed geometry rewrites (auto-satin, convert, flip, route, ...)."""


# Scale-preservation contract per tool: allowed relative span deviation for
# svg/units.py check_scale_drift (that module documents the measured engine
# px-space write bug this refuses).
#
#   strict — routing tools rewrite every element but must keep the art's
#            scale exactly (5% span tolerance covers stitch-path jitter).
#   loose  — centerline-ish converters keep spans within a stroke/band
#            width, so only a multiplicative rescale (>1.5×) is refused.
#   None   — the span comparison is meaningless: cleanup removes elements,
#            and stroke_to_satin legitimately collapses a zigzag run's span
#            to the satin band around its spine (measured 20 → 6.6 units on
#            a plain wavy stroke).
_SCALE_GUARD = {
    "auto_run": 0.05,
    "auto_satin": 0.05,
    "stroke_to_satin": None,
    "satin_to_stroke": 0.5,
    "flip": 0.5,
    "break_apart": 0.5,
    "cleanup": None,
}


def _strip_stale_underpaths(tree, ids):
    """Remove previous auto_run travel output before re-routing.

    The engine's router treats every Stroke it is given as art to cover
    (lib/stitches/auto_run.py autorun/_process_elements — no path_type
    filtering on input) and its create_element writes
    inkstitch:path_type='autorun-underpath' on the travel runs it generates.
    Feeding those back in re-routes travel as art: measured on the rose-bag
    design, 129 inputs became 320 elements with bean-stitched travel legs
    crossing empty fabric.  Travel is regenerated by every routing pass, so
    stale underpaths are dropped here (from both the document and the
    selection) rather than routed.
    """
    from cli_anything_inkstitch.svg.attrs import qname
    key = qname("path_type")
    removed = []
    for elem in list(tree.getroot().iter()):
        if elem.get(key) == "autorun-underpath":
            removed.append(elem.get("id") or "?")
            elem.getparent().remove(elem)
    kept_ids = [i for i in ids if i not in set(removed)]
    return kept_ids, removed


def _run_tool(ctx, project_path, extension_name, ids, args, *, pre_process=None):
    emit(ctx, run_tool_core(ctx, project_path, extension_name, ids, args,
                            pre_process=pre_process))


def run_tool_core(ctx, project_path, extension_name, ids, args, *,
                  pre_process=None) -> dict:
    """Run a binary tool; if it returns SVG, swap it in. Returns the payload.

    Uses mutate=False — we save the SVG ourselves so open_project's exit-save
    doesn't clobber the binary's output with the original tree.
    """
    from cli_anything_inkstitch.svg.document import save_svg
    from cli_anything_inkstitch.svg.attrs import ensure_inkstitch_namespace
    from cli_anything_inkstitch.svg.units import (
        art_bbox,
        bake_transforms,
        check_scale_drift,
        unit_scale_warning,
    )
    with open_project(ctx, project_path, mutate=False) as (proj, _tree):
        binary = require(ctx.obj.get("binary_override"), proj.session)
        # snapshot for history BEFORE any pre-processing mutates the tree,
        # so undo restores the document exactly as it was
        before_xml = etree.tostring(_tree.getroot()).decode("utf-8")
        before_bbox = art_bbox(_tree)
        # routing rewrites the whole document; take a durable auto-checkpoint
        # so a bad pass is one restore away even after the history ring
        # forgets (checkpoints.py — a re-route once turned 129 elements into
        # 320 with no undo path left)
        if extension_name in ("auto_run", "auto_satin"):
            from cli_anything_inkstitch.checkpoints import record_checkpoint
            record_checkpoint(proj, _tree,
                              f"auto: before {extension_name}", auto=True)
            proj.save()
        unit_warning = unit_scale_warning(_tree.getroot())
        extra_payload = {}
        if pre_process is not None:
            ids, extra_payload = pre_process(_tree, ids)
            if extra_payload:
                # pre-processing changed the document — the binary reads from
                # disk, so flush before invoking it
                save_svg(_tree, proj.svg_path)
        stdout = run_extension(binary, extension_name, proj.svg_path,
                                args=args, ids=ids, capture_stdout=True)
        if not stdout:
            if extra_payload:
                # pre-processing already changed the doc; record + keep it
                push(proj.history, make_entry(
                    command=f"tools {extension_name} (pre-process only)",
                    patch=document_replace(
                        before_xml,
                        etree.tostring(_tree.getroot()).decode("utf-8"))))
                proj.svg_sha256 = save_svg(_tree, proj.svg_path)
                proj.save()
            # Empty stdout = nothing applicable; not an error.
            return {"tool": extension_name, "ids": ids, "changed": bool(extra_payload),
                    "note": "no changes — selection may not match tool requirements",
                    **extra_payload}
        new_tree = etree.ElementTree(etree.fromstring(stdout))
        ensure_inkstitch_namespace(new_tree)
        # engine tools may leave their px-space correction transform as an
        # attribute (svg/units.py has the measured details) — bake it so raw
        # path data equals effective geometry for every downstream reader
        baked = bake_transforms(new_tree)
        # refuse silently-rescaled output before it reaches the document —
        # see _SCALE_GUARD for the measured engine behavior this catches
        tol = _SCALE_GUARD.get(extension_name, 0.5)
        try:
            if tol is not None:
                check_scale_drift(extension_name, before_bbox,
                                  art_bbox(new_tree), tol)
        except UserError:
            # roll the on-disk SVG back to the pre-tool state (pre_process
            # may have flushed a mutated tree above)
            if extra_payload:
                restored = etree.ElementTree(
                    etree.fromstring(before_xml.encode("utf-8")))
                save_svg(restored, proj.svg_path)
            raise
        # binary tools rewrite the whole document — record it so undo/redo
        # and the artifact History panel see it like any other edit
        push(proj.history, make_entry(
            command=f"tools {extension_name}" + (f" --ids {','.join(ids)}" if ids else ""),
            patch=document_replace(
                before_xml,
                etree.tostring(new_tree.getroot()).decode("utf-8"))))
        proj.svg_sha256 = save_svg(new_tree, proj.svg_path)
        proj.save()
        payload = {"tool": extension_name, "ids": ids, "changed": True,
                   "bytes": len(stdout), **extra_payload}
        if baked:
            payload["baked_transforms"] = baked
        if unit_warning:
            payload["unit_warning"] = unit_warning
        return payload


@tools.command("auto-satin")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.option("--ids", "ids_csv", required=True)
@click.option("--trim/--no-trim", default=True)
@click.option("--preserve-order", is_flag=True)
@click.option("--keep-originals", is_flag=True)
@click.pass_context
def auto_satin(ctx, project_path, ids_csv, trim, preserve_order, keep_originals):
    ids = [s.strip() for s in ids_csv.split(",") if s.strip()]
    args = {
        "trim": str(trim).lower(),
        "preserve_order": str(preserve_order).lower(),
        "keep_originals": str(keep_originals).lower(),
    }
    _run_tool(ctx, project_path, "auto_satin", ids, args)


@tools.command("convert-to-satin")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.option("--ids", "ids_csv", required=True)
@click.pass_context
def convert_to_satin(ctx, project_path, ids_csv):
    ids = [s.strip() for s in ids_csv.split(",") if s.strip()]
    _run_tool(ctx, project_path, "stroke_to_satin", ids, {})


@tools.command("convert-satin-to-stroke")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.option("--ids", "ids_csv", required=True)
@click.option("--keep-satin", is_flag=True)
@click.pass_context
def convert_satin_to_stroke(ctx, project_path, ids_csv, keep_satin):
    ids = [s.strip() for s in ids_csv.split(",") if s.strip()]
    _run_tool(ctx, project_path, "satin_to_stroke", ids,
              {"keep_satin": str(keep_satin).lower()})


@tools.command("flip-satin")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.option("--id", "svg_id", required=True)
@click.pass_context
def flip_satin(ctx, project_path, svg_id):
    _run_tool(ctx, project_path, "flip", [svg_id], {})


@tools.command("auto-run")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.option("--ids", "ids_csv", required=True)
@click.option("--trim/--no-trim", default=False)
@click.option("--preserve-order", is_flag=True)
@click.option("--break-up/--no-break-up", default=True)
@click.option("--keep-underpaths", is_flag=True,
              help="Do not drop previous auto-run travel elements before "
                   "routing (they will be re-routed as art — rarely wanted).")
@click.pass_context
def auto_run(ctx, project_path, ids_csv, trim, preserve_order, break_up,
             keep_underpaths):
    ids = [s.strip() for s in ids_csv.split(",") if s.strip()]

    def _pre(tree, ids_in):
        kept, removed = _strip_stale_underpaths(tree, ids_in)
        if not removed:
            return ids_in, {}
        return kept, {"removed_stale_underpaths": removed}

    _run_tool(ctx, project_path, "auto_run", ids, {
        "trim": str(trim).lower(),
        "preserve_order": str(preserve_order).lower(),
        "break_up": str(break_up).lower(),
    }, pre_process=None if keep_underpaths else _pre)


@tools.command("break-apart")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.option("--id", "svg_id", required=True)
@click.pass_context
def break_apart(ctx, project_path, svg_id):
    _run_tool(ctx, project_path, "break_apart", [svg_id], {})


@tools.command("cleanup")
@click.option("--project", "project_path", type=click.Path(), default=None)
@click.pass_context
def cleanup(ctx, project_path):
    _run_tool(ctx, project_path, "cleanup", [], {})


@tools.command("digitize-lineart")
@click.option("--project", "project_path", required=True, type=click.Path())
@click.option("--image", "image_path", required=True, type=click.Path(),
              help="Source raster (line art; dark strokes on light ground).")
@click.option("--width-mm", type=float, default=None)
@click.option("--height-mm", type=float, default=None,
              help="Physical size; give one, the other follows the aspect.")
@click.option("--threshold", type=int, default=128, show_default=True)
@click.option("--spur-ink-threshold", type=float, default=0.5, show_default=True,
              help="Strokes whose on-ink fraction falls below this are "
                   "tracing spurs and get removed (after the overlay render).")
@click.option("--stitch-length-mm", type=float, default=2.5, show_default=True)
@click.option("--bean-repeats", type=int, default=1, show_default=True)
@click.option("--route/--no-route", default=True, show_default=True,
              help="auto-run routing + top styling after verification.")
@click.option("--trim/--no-trim", default=True, show_default=True)
@click.pass_context
def digitize_lineart(ctx, project_path, image_path, width_mm, height_mm,
                     threshold, spur_ink_threshold, stitch_length_mm,
                     bean_repeats, route, trim):
    """Digitize raster line art into a verified stroke-only design.

    Pipeline (trace/lineart.py documents each stage's rationale):
    threshold → vtracer trace → px-unit document → engine centerlines →
    ink-fraction spur sweep (overlay PNG rendered BEFORE deleting) →
    reverse coverage recovery of dropped thin marks → auto-run + bean
    styling → gate.  Every geometric step is verified against the source
    raster; the overlay PNG is the human-checkable record.
    """
    from cli_anything_inkstitch.artifact.design_model import (
        apply_edits,
        read_design,
    )
    from cli_anything_inkstitch.artifact.gate import flatten_path, run_gate
    from cli_anything_inkstitch.project import (
        ProjectFile,
        project_lock,
        require_absolute,
    )
    from cli_anything_inkstitch.svg.document import save_svg, sha256_of
    from cli_anything_inkstitch.svg.geometry import transform_d
    from cli_anything_inkstitch.trace import lineart

    if (width_mm is None) == (height_mm is None):
        raise UserError("give exactly one of --width-mm / --height-mm "
                        "(the other follows the source aspect ratio)")

    project_path = require_absolute(project_path, "project")
    from pathlib import Path
    stem = Path(project_path).with_suffix("")
    if str(stem).endswith(".inkstitch-cli"):
        stem = Path(str(stem)[: -len(".inkstitch-cli")])
    bw_path = Path(f"{stem}-bw.png")
    traced_path = Path(f"{stem}-traced.svg")
    svg_path = Path(f"{stem}.svg")
    overlay_path = Path(f"{stem}-overlay.png")

    # 1-3: raster → binarized crop → traced outlines → px-unit document
    img = lineart.threshold_image(image_path, threshold=threshold)
    img.save(bw_path)
    lineart.trace_to_svg(bw_path, traced_path)
    tree, kd = lineart.build_px_document(traced_path, img.size,
                                         width_mm, height_mm)
    fill_count = sum(1 for _ in tree.getroot().iter(
        "{http://www.w3.org/2000/svg}path"))

    with project_lock(project_path):
        proj, _created = ProjectFile.load_or_create(project_path)
        if proj.svg_path and proj.svg_path != str(svg_path):
            raise UserError(
                f"project already attached to {proj.svg_path}; use a fresh "
                "project file for digitize-lineart")
        proj.svg_sha256 = save_svg(tree, str(svg_path))
        proj.svg_path = str(svg_path)
        proj.save()

    # 4: engine centerlines (convert_element runs fill_to_stroke with the
    # bake + scale guard from svg/units.py)
    for i in range(1, fill_count + 1):
        apply_edits(project_path, [
            {"op": "convert_element", "id": f"elem_{i}", "to": "run"}])

    # 5: align art onto the raster's pixel grid so kd maps geometry ↔ ink
    # (the engine writes px-space absolute coordinates; position must be
    # measured, never assumed)
    def strokes():
        return [(o["id"], flatten_path(o["d"]))
                for o in read_design(project_path)["objects"]
                if len(flatten_path(o["d"])) >= 2]

    pts_all = [p for _sid, pts in strokes() for p in pts]
    if not pts_all:
        raise UserError("centerline extraction produced no strokes")
    dx = 0.0 - min(p[0] for p in pts_all)
    dy = 0.0 - min(p[1] for p in pts_all)
    ink = lineart.ink_bbox(img)
    dx += ink[0] * kd
    dy += ink[1] * kd
    if abs(dx) > 0.01 or abs(dy) > 0.01:
        apply_edits(project_path, [
            {"op": "set_path", "id": o["id"],
             "d": transform_d(o["d"], (1, 0, 0, 1, dx, dy))}
            for o in read_design(project_path)["objects"]])

    # 6: stroke→ink verification; overlay rendered BEFORE any deletion
    scored = [(lineart.ink_fraction(pts, img, kd), sid, pts)
              for sid, pts in strokes()]
    suspects = [(sid, pts) for f, sid, pts in scored if f < spur_ink_threshold]
    kept = [(sid, pts) for f, sid, pts in scored if f >= spur_ink_threshold]

    def to_src(pts):
        return [(x / kd, y / kd) for x, y in pts]

    # 7: ink→stroke verification — recover thin marks the trace/centerline
    # pass dropped
    mask = lineart.stroke_cover_mask(
        img.size, [to_src(pts) for _sid, pts in kept])
    missed = lineart.uncovered_ink_components(img, mask)
    added_ids = []
    added_src = []
    for comp in missed:
        line = lineart.component_centerline(comp)
        added_src.append(line)
        d = "M " + " L ".join(f"{x * kd:.2f},{y * kd:.2f}" for x, y in line)
        r = apply_edits(project_path, [
            {"op": "add_element", "d": d, "kind": "run", "color": "#1a1a1a"}])
        added_ids.append(r["results"][0]["id"])

    lineart.overlay_png(img,
                        kept_src=[to_src(pts) for _sid, pts in kept],
                        suspects_src=[to_src(pts) for _sid, pts in suspects],
                        added_src=added_src,
                        out_path=overlay_path)
    for sid, _pts in suspects:
        apply_edits(project_path, [{"op": "delete_element", "id": sid}])

    payload = {
        "project": project_path,
        "svg": str(svg_path),
        "overlay": str(overlay_path),
        "traced_fills": fill_count,
        "strokes": len(kept) + len(added_ids),
        "spurs_removed": [sid for sid, _ in suspects],
        "recovered_marks": added_ids,
    }

    # 8: route + style
    if route:
        ids = [o["id"] for o in read_design(project_path)["objects"]]

        def _pre(t, ids_in):
            kept_ids, removed = _strip_stale_underpaths(t, ids_in)
            return (kept_ids, {"removed_stale_underpaths": removed}) \
                if removed else (ids_in, {})

        route_payload = run_tool_core(
            ctx, project_path, "auto_run", ids,
            {"trim": str(trim).lower(), "preserve_order": "false",
             "break_up": "true"}, pre_process=_pre)
        payload["routed"] = route_payload.get("changed", False)

        styled = _style_autorun_tops(ctx, project_path, stitch_length_mm,
                                     bean_repeats)
        payload.update(styled)

    gate = run_gate(project_path)
    payload["gate_ok"] = gate.get("ok")
    payload["gate_issues"] = len(gate.get("issues", []))
    emit(ctx, payload)


def _style_autorun_tops(ctx, project_path, stitch_length_mm, bean_repeats):
    """Bean-style every autorun-top in one history entry (undo-atomic)."""
    from cli_anything_inkstitch.binary import installed_version
    from cli_anything_inkstitch.commands._helpers import record, xpath_for_id
    from cli_anything_inkstitch.commands.params import _apply_params_to_element
    from cli_anything_inkstitch.history import attr_diff, multi_patch
    from cli_anything_inkstitch.schema.cache import load_schema
    from cli_anything_inkstitch.svg.attrs import qname
    from cli_anything_inkstitch.svg.elements import classify, set_params_on

    schema = load_schema(prefer_version=installed_version(None))
    extra = {"bean_stitch_repeats": str(bean_repeats),
             "running_stitch_length_mm": str(stitch_length_mm)}
    patches = []
    styled = []
    errors = []
    with open_project(ctx, project_path, mutate=True) as (proj, tree):
        key = qname("path_type")
        tops = [e for e in tree.getroot().iter()
                if e.get(key) == "autorun-top" and e.get("id")]
        for elem in tops:
            # recovered marks re-routed by the engine may come back without
            # stroke paint (style copied from a paint-less input) — classify
            # needs it, so restore paint before applying params
            try:
                before, after = _apply_params_to_element(
                    elem, None, extra, schema, force=False)
            except UserError:
                elem.set("fill", "none")
                elem.set("stroke", elem.get("stroke") or "#1a1a1a")
                try:
                    before, after = _apply_params_to_element(
                        elem, "running_stitch", extra, schema, force=False)
                except UserError as exc:
                    errors.append({"id": elem.get("id"), "error": str(exc)})
                    continue
            if after:
                patches.append(attr_diff(xpath_for_id(elem.get("id")),
                                         before, after))
            styled.append(elem.get("id"))
            proj.elements.setdefault(elem.get("id"), {})
            proj.elements[elem.get("id")]["stitch_type"] = classify(elem)
            proj.elements[elem.get("id")]["set_params"] = set_params_on(elem)
        if patches:
            record(proj.history,
                   f"tools digitize-lineart style ({len(styled)} tops)",
                   multi_patch(patches))
    return {"styled_tops": len(styled), "style_errors": errors}
